-- 에러코드 --
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00000', 'Api processing success', 'SUCCESS');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00001', 'Parameter is invalid', 'INVALID_PARAMETER');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00002', 'User id already registered', 'REGISTERED_ID');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00003', 'Partner does not exist', 'NO_PARTNER');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00004', 'Barcode does not exist', 'NO_BARCODE');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00005', 'Remain point amount is not sufficient', 'NOT_ENOUGH_POINT');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('00006', 'There is no point history for requested barcode for requested dates', 'NO_POINT_HISTORY');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('99998', 'Request transaction failed', 'TRANSACTION_ERROR');
INSERT INTO CODE_DATA (ERROR_CODE, ERROR_MSG, REASON_KEY) VALUES ('99999', 'Api general error', 'API_GENERAL_ERROR');

-- 상점정보 --
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('A', 'grocery1', '식품점1');
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('A', 'grocery2', '식품점2');
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('B', 'cosmetics1', '화장품점1');
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('B', 'cosmetics2', '화장품점2');
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('C', 'restaurant1', '식당1');
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('C', 'restaurant2', '식당2');
INSERT INTO SHOP (CATEGORY, PARTNER_ID, PARTNER_NAME) VALUES ('A', 'testshop', '테스트상점');

-- 멤버십정보 --
INSERT INTO MEMBERSHIP (MEMBERSHIP_SEQ, USER_ID, BARCODE, TID, ORDERID) VALUES ('100000', '200000000', 'ABCDEFGHIJ', 'TESTTID', 'TESTORDERID');

-- 사용내역 --
INSERT INTO POINT (POINT_SEQ, MEMBERSHIP_SEQ, TID, ORDERID, PARTNER_ID, PARTNER_NAME, USER_ID, BARCODE, CATEGORY, TYPE, POINT_AMOUNT) VALUES ('100000', '100000', 'TESTTID',
'TESTORDERID', 'testshop', '테스트상점', '200000000', 'ABCDEFGHIJ', 'A', 'earn', '1000');

-- 멤버십포인트 --
INSERT INTO MEMBER_POINT (MEMBER_POINT_SEQ, USER_ID, CATEGORY, CATEGORY_ID, TOTAL_POINT, VERSION) VALUES ('100000', '200000000', 1, 'GROCERY', '1000', '1');